-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 10:28:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spring_boot_crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spring_boot_crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_boot_crm` DEFAULT CHARACTER SET utf8 ;
USE `spring_boot_crm` ;

-- -----------------------------------------------------
-- Table `spring_boot_crm`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `subordination_level` INT NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  `departments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_positions_departmens1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_positions_departmens1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `spring_boot_crm`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`phone_number_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`phone_number_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `birthday` TIMESTAMP NOT NULL,
  `contract_start` TIMESTAMP NOT NULL,
  `contract_finish` TIMESTAMP NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `tgid` INT NULL,
  `dov` VARCHAR(70) NULL,
  `comment` VARCHAR(255) NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  `cities_id` INT NOT NULL,
  `positions_id` INT NOT NULL,
  `departments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_cities_idx` (`cities_id` ASC) VISIBLE,
  INDEX `fk_users_positions1_idx` (`positions_id` ASC) VISIBLE,
  INDEX `fk_users_departmens1_idx` (`departments_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_users_cities`
    FOREIGN KEY (`cities_id`)
    REFERENCES `spring_boot_crm`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `spring_boot_crm`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_departmens1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `spring_boot_crm`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`employees_phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`employees_phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(55) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  `phone_number_types_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_phones_phone_number_types1_idx` (`phone_number_types_id` ASC) VISIBLE,
  INDEX `fk_employees_phones_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_phones_phone_number_types1`
    FOREIGN KEY (`phone_number_types_id`)
    REFERENCES `spring_boot_crm`.`phone_number_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_phones_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`users_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`users_has_roles` (
  `users_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `roles_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `spring_boot_crm`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `other` VARCHAR(255) NULL,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `status` VARCHAR(55) NULL,
  `cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auto_cities1_idx` (`cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_auto_cities1`
    FOREIGN KEY (`cities_id`)
    REFERENCES `spring_boot_crm`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`ltd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`ltd` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `status` VARCHAR(55) NULL,
  `name_full` VARCHAR(255) NULL,
  `name_short` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `unp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_full_UNIQUE` (`name_full` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`ltd_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`ltd_bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(55) NULL,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `requisites` VARCHAR(500) NULL,
  `ltd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ltd_bank_ltd1_idx` (`ltd_id` ASC) VISIBLE,
  CONSTRAINT `fk_ltd_bank_ltd1`
    FOREIGN KEY (`ltd_id`)
    REFERENCES `spring_boot_crm`.`ltd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`ltd_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`ltd_contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_start` TIMESTAMP NULL,
  `number` VARCHAR(100) NULL,
  `other` VARCHAR(255) NULL,
  `status` VARCHAR(55) NULL,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `ltd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ltd_contract_ltd1_idx` (`ltd_id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `fk_ltd_contract_ltd1`
    FOREIGN KEY (`ltd_id`)
    REFERENCES `spring_boot_crm`.`ltd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`ltd_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`ltd_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `status` VARCHAR(55) NULL,
  `type` INT NULL,
  `distance_main_office` INT NULL,
  `distance_local_office` INT NULL,
  `others` VARCHAR(255) NULL,
  `telecom_cabinet` INT NULL,
  `ups` INT NULL,
  `server` INT NULL,
  `switch` INT NULL,
  `workplace` INT NULL,
  `equipment` INT NULL,
  `ltd_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ltd_instance_ltd1_idx` (`ltd_id` ASC) VISIBLE,
  INDEX `fk_ltd_instance_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_ltd_instance_cities1_idx` (`cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_ltd_instance_ltd1`
    FOREIGN KEY (`ltd_id`)
    REFERENCES `spring_boot_crm`.`ltd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ltd_instance_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ltd_instance_cities1`
    FOREIGN KEY (`cities_id`)
    REFERENCES `spring_boot_crm`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`ticket_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`ticket_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `status` VARCHAR(55) NULL,
  `name` VARCHAR(100) NULL,
  `action` INT NULL,
  `priority` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `open_status` INT NULL,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  `status` VARCHAR(55) NULL,
  `date_of_receiving` TIMESTAMP NULL,
  `date_of_finish` TIMESTAMP NULL,
  `date_customers_department_doc` TIMESTAMP NULL,
  `date_accounting_department_doc` TIMESTAMP NULL,
  `date_transfer_doc` TIMESTAMP NULL,
  `system_ticket_id` VARCHAR(70) NULL,
  `waybill` VARCHAR(45) NULL,
  `server` INT NULL,
  `ups` INT NULL,
  `switch` INT NULL,
  `workplace` INT NULL,
  `equipment` INT NULL,
  `employee_executor_dov` VARCHAR(70) NULL,
  `job` VARCHAR(255) NULL,
  `other` VARCHAR(255) NULL,
  `auto_id` INT NULL,
  `ltd_instance_id` INT NOT NULL,
  `employee_executor_id` INT NULL,
  `employee_owner_id` INT NOT NULL,
  `employee_recipient_id` INT NULL,
  `ticket_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_auto1_idx` (`auto_id` ASC) VISIBLE,
  INDEX `fk_tickets_ltd_instance1_idx` (`ltd_instance_id` ASC) VISIBLE,
  INDEX `fk_tickets_users1_idx` (`employee_executor_id` ASC) VISIBLE,
  INDEX `fk_tickets_users2_idx` (`employee_owner_id` ASC) VISIBLE,
  INDEX `fk_tickets_users3_idx` (`employee_recipient_id` ASC) VISIBLE,
  INDEX `fk_tickets_ticket_type1_idx` (`ticket_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `spring_boot_crm`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_ltd_instance1`
    FOREIGN KEY (`ltd_instance_id`)
    REFERENCES `spring_boot_crm`.`ltd_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users1`
    FOREIGN KEY (`employee_executor_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users2`
    FOREIGN KEY (`employee_owner_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users3`
    FOREIGN KEY (`employee_recipient_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `spring_boot_crm`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring_boot_crm`.`jwt_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_boot_crm`.`jwt_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL,
  `status` VARCHAR(55) NOT NULL,
  `token` VARCHAR(450) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jwt_token_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_jwt_token_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spring_boot_crm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
